export type PortfolioImage = { src: string; alt: string }
export type Project = { id: string; name: string; category: string; description: string; details: string[]; technologies: string[]; image: PortfolioImage; url: string }
export type Certificate = { id: string; title: string; issuer: string; date: string; description: string; image: PortfolioImage; url: string }
export type Activity = { id: string; title: string; category: string; location: string; date: string; description: string[]; highlights: string[]; images: PortfolioImage[] }

export const projects: Project[] = [
  {
    id: 'formguard', name: 'FormGuard-Insight', category: 'OFFLINE-FIRST · APPLIED AI', description: 'An offline-first, AI-assisted validation platform supporting Student, Hospital, and Store forms.', details: ['Built an advanced offline data-validation system that uses AI scoring, behavioral heuristics, and dynamic form rules to ensure high-integrity data entry in low-connectivity environments. Features include live anomaly detection, multi-form validation (Student/Hospital/Store), role-based review workflow, interactive analytics, export tools (CSV/JSON/PDF), and full offline storage using IndexedDB. Designed with React, Tailwind, Framer Motion, and Chart.js to deliver a secure, smooth, and highly interactive user experience.'], technologies: ['Vite', 'TypeScript', 'React', 'Tailwind CSS', 'shadcn - ui'], image:
      { src: '/images/form.png', alt: 'FormGuard-Insight project preview' }, url: 'https://formguard-insight-t7xy.vercel.app/?_vercel_share=hoItwvxnonzGa9NlI5PUizqYszHp9ShH'
  },
  {
    id: 'medibuddy', name: 'MediBuddy v2', category: 'MULTI-AGENT SYSTEMS · HEALTHCARE', description: 'An AI multi-agent medication assistant focused on personalized reminders, adherence tracking, and patient engagement.', details: ['Adherence Assistant Kaggle Project ,Designed an AI multi-agent system to improve medication adherence using intelligent task coordination. Implemented agents for reminder scheduling, user interaction, and adherence tracking. Utilized machine learning and rule-based logic to personalize medication alerts and monitor missed doses. Analyzed user behavior data to generate adherence insights and reports. Focused on real-world healthcare use cases, improving reliability and user engagement.'], technologies: ['Python', 'Machine Learning', 'Data Analysis', 'Kaggle', 'Multi-Agent Systems'], image:
      { src: '/images/medi.png', alt: 'MediBuddy v2 project preview' }, url: 'https://v0-medi-buddy-v2-project.vercel.app/'
  },
  {
    id: 'blue-insights', name: 'Blue Insights', category: 'MARINE DATA · MACHINE LEARNING', description: 'A unified AI marine analytics platform integrating oceanographic, fisheries, and satellite datasets.', details: ['AI-Driven Unified Marine Data Platform Smart India Hackathon 2025 | Team aquadata Developed an AI-powered unified data platform integrating oceanographic data (temperature, salinity, satellite), fisheries data, and molecular biodiversity (eDNA) into a single system. Designed an end-to-end framework to transform raw marine data into actionable insights, including fish stock prediction, algal bloom risk assessment, and biodiversity hotspot identification. Applied machine learning and data analytics to support real-time monitoring and predictive stock prediction, algal bloom risk assessment, and biodiversity hotspot identification. Applied machine learning and data analytics to support real-time monitoring and predictive decision-making for scientists, policymakers, and fisheries managers. Aligned the solution with Indias Blue Economy vision and SDG-14 (Life Below Water), focusing on sustainability, marine conservation, and data-driven governance.'], technologies: ['Docker', 'Machine Learning', 'Data Pipelines'], image:
      { src: '/images/bl.png', alt: 'Blue Insights project preview' }, url: 'https://sih-project-psi-seven.vercel.app/?_vercel_share=NZsAuazYbJj8DfB8Oj5lwDrRpaRLtrZP'
  },
  {
    id: 'jarvis', name: 'J.A.R.V.I.S', category: 'PROJECT ARCHIVE', description: 'Project overview to be added.', details: ['Developed JARVIS, a voice-controlled AI assistant capable of understanding natural language commands and executing system-level operations. The assistant runs in a console-based environment and uses LiveKit Agents for real-time audio processing and Google Gemini for intelligent reasoning. Implemented a tool-based architecture to safely perform actions such as opening files, checking battery status, and retrieving information via web search, while maintaining strict control over system access. '], technologies: ['Python', 'Google Gemini API', 'Livekit AI'], image:
      { src: '/images/jarvis.png', alt: 'J.A.R.V.I.S project preview' }, url: ''
  },
  {
    id: 'digifoot', name: 'DigiFoot', category: 'COMPUTER VISION · 3D RECONSTRUCTION', description: 'An AI 3D foot scanning system that reconstructs foot models from smartphone images.', details: ['Developed DigiFoot, an AI-powered 3D foot scanning and analysis application that uses smartphone cameras to generate accurate digital foot models and measurements. The application performs real-time image capture and 3D reconstruction using Computer Vision, OpenCV, Open3D, and Machine Learning techniques for detailed foot analysis. Implemented features such as foot measurement extraction, 3D visualization, AI-based model refinement, and export support for applications in custom footwear, orthopedic analysis, and foot health monitoring. '], technologies: ['Python', 'OpenCV', 'Open3D', 'PyTorch'], image:
      { src: '/images/digifoot.png', alt: 'DigiFoot project preview' }, url: ''
  },
]

export const certificates: Certificate[] = [
  { id: 'oracle-foundations', title: 'Oracle AI Foundations Associate', issuer: 'Oracle', date: '', description: '', image: { src: '/images/cer1.png', alt: 'Oracle AI Foundations Associate certificate' }, url: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=F5D6C48AA87252D32EF01CB232121A1B85BC0C565604E60F17A71F9FA27F40CA' },
  { id: 'oracle-generative', title: 'Oracle Generative AI Professional', issuer: 'Oracle', date: '', description: '', image: { src: '/images/cer2.png', alt: 'Oracle Generative AI Professional certificate' }, url: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=766319ABEA43094EE3A29C7A325102007BD60DB9933A50AD9DF30142A2C5914F' },
  { id: 'generative-intro', title: 'Introduction to Generative AI', issuer: 'Google Cloud', date: '', description: '', image: { src: '/images/cer3.png', alt: 'Introduction to Generative AI certificate' }, url: 'https://simpli-web.app.link/e/dUDBHKyXkYb' },
  { id: 'operating-systems', title: 'Introduction to Operating Systems Specialization', issuer: 'Codio', date: '', description: '', image: { src: '/images/cer4.png', alt: 'Introduction to Operating Systems Specialization certificate' }, url: 'https://www.coursera.org/account/accomplishments/specialization/O8FT9R64KU63' },
  { id: 'cybersecurity', title: 'Foundations of Cybersecurity', issuer: 'Google', date: '', description: '', image: { src: '/images/cer5.png', alt: 'Foundations of Cybersecurity certificate' }, url: 'https://www.coursera.org/account/accomplishments/records/SKAVJTD5T3KF' },
  { id: 'google-agents', title: '5-Day AI Agents Intensive Course with Google', issuer: 'Kaggle', date: '', description: '', image: { src: '/images/cer6.png', alt: '5-Day AI Agents Intensive Course with Google certificate' }, url: 'https://www.kaggle.com/certification/badges/piyushbipinvarule/105' },
]

export const activities: Activity[] = [
  {
    id: 'cloud-pune', title: 'Cloud Community — Pune', category: 'COMMUNITY · EXPLORATION', location: 'Pune, India', date: '', description: ['Cloud Community Pune was the 8th flagship Cloud Community event in India.', 'I recently had the opportunity to attend the Claude Community Pune meetup by Anthropic, the 8th flagship Claude Community event in India. The event went beyond presentations, offering an open space for builders to share real experiences, experiments, failures, and ideas around AI. Highlights included Claude Unfiltered, covering prompt injections, jailbreaking, LLM security, Agent SDKs, and real-world failure stories, along with builder demos and conversations showcasing how developers are experimenting with Claude and turning ideas into practical solutions. As an engineering student exploring AI, automation, and software development, the meetup gave me valuable insight into the rapidly evolving AI ecosystem. My biggest takeaway: don’t just learn about AI—build with it, experiment with it, and learn from what breaks. I’m grateful to the organizers and community for creating such an open, practical environment for learning and networking, and I look forward to building, experimenting, and being part of more communities like this.'], highlights: ['Cloud Unfiltered', 'Builder demos', 'Meaningful conversations'],
    images: [{ src: '/images/c1.png', alt: 'Cloud Community Pune event photo 1' }, { src: '/images/c2.png', alt: 'Cloud Community Pune event photo 2' }, { src: '/images/c3.png', alt: 'Cloud Community Pune event photo 3' }]
  },
  {
    id: 'code-society', title: 'Code 4 Society Hackathon', category: 'VOLUNTEERING · HACKATHON', location: 'Pimpri Chinchwad University', date: '', description: ['I’m happy to share that I had the opportunity to volunteer at the Code4Society Hackathon, a 3-day event organized by the Blockchain Club:',
      'Chain Alchemy and the CSE-AI&ML Department at Pimpri Chinchwad University. 🚀 During the event, I supported participants, assisted with event operations, and witnessed innovative ideas being developed by talented teams. It was inspiring to see collaboration, creativity, and technology come together to solve real-world problems. 💡 I’m grateful to the organizers and faculty members for this opportunity and for recognizing my contribution with a Certificate of Appreciation. 🏆 This experience helped me strengthen my understanding of teamwork, event management, and the dynamic environment of hackathons. I look forward to participating in more such events, contributing to the tech community, and continuing to learn and grow. 🌟'], highlights: ['Participant support', 'Event operations', 'Three-day hackathon'],
    images: [{ src: '/images/code1.png', alt: 'Code 4 Society Hackathon photo 1' }, { src: '/images/code2.png', alt: 'Code 4 Society Hackathon photo 2' }]
  },
  {
    id: 'techfest', title: 'TechFest — IIT Bombay', category: 'LEARNING · ACHIEVEMENT', location: 'IIT Bombay, Mumbai', date: '', description: ['I recently had the opportunity to attend a TechFest at IIT Bombay, where I explored the fundamentals of Generative AI and gained valuable insights into various AI modules shaping modern technology.', 'The sessions helped me understand how AI models work, how different components come together, and how these technologies can be applied to real-world problem-solving across multiple domains. I’m also excited to share that I won the quiz competition conducted during the event, making the experience even more rewarding. 🏆 This experience strengthened my curiosity and motivation to explore AI and Machine Learning more deeply. I’m grateful for the learning, challenges, and inspiration, and I look forward to applying these insights while continuing to grow in the field of technology. 🚀'], highlights: ['Generative AI', 'AI model fundamentals', 'Quiz competition winner'],
    images: [{ src: '/images/tech1.png', alt: 'TechFest IIT Bombay photo 1' }, { src: '/images/tech2.png', alt: 'TechFest IIT Bombay photo 2' }, { src: '/images/tech3.png', alt: 'TechFest IIT Bombay photo 3' }]
  },
]

export const experience = [
  { role: 'Freelance AI/ML Developer', organization: 'Self-Employed · Freelance', date: 'Mar 2026 — Apr 2026', details: ['Developed an AI-powered computer vision application to generate 3D foot models from smartphone images using Python, OpenCV, Open3D, and PyTorch.', 'Implemented image acquisition, 3D reconstruction, automated measurement extraction, and visualization modules, with export support for measurements and models.'] },
  { role: 'Technical Content & Research Intern', organization: 'Amigoes Foundation', date: 'May 2025 — Jun 2025', details: ['Researched technical and awareness topics to produce SEO-optimized content across digital campaigns.', 'Collaborated with editors to improve structure and readability, created documentation from verified sources, and consistently met project deadlines.'] },
]

export const skillGroups = [
  { title: 'Languages & foundations', kind: 'code', skills: ['Python', 'JavaScript', 'TypeScript', 'C++', 'C', 'Java', 'DSA'] },
  { title: 'Web & interface', kind: 'web', skills: ['HTML5', 'CSS3', 'React', 'Tailwind CSS', 'Bootstrap', 'UI/UX'] },
  { title: 'AI & automation', kind: 'ai', skills: ['Artificial Intelligence', 'Machine Learning', 'Multi-Agent Systems', 'Generative AI', 'NLP', 'Prompt Engineering', 'Automation', 'PyTorch', 'OpenCV', 'Open3D'] },
  { title: 'Data & developer tools', kind: 'data', skills: ['MySQL', 'MongoDB', 'Data Analysis', 'NumPy', 'FastAPI', 'Docker', 'VS Code'] },
  { title: 'Communication', kind: 'writing', skills: ['Content Writing', 'SEO', 'Technical Research'] },
] as const
